# CodeRabbit Configuration - only non-default values
# Defaults: https://coderabbit.ai/integrations/schema.v2.json

reviews:
  auto_review:
    # Only review on PR open, not every push (default: true)
    auto_incremental_review: false

  # Skip non-code files
  path_filters:
    - "!.state/**"
    - "!*.md"

chat:
  # Don't auto-reply to comments (default: true)
  auto_reply: false
