# CodeRabbit Configuration
# https://docs.coderabbit.ai/reference/configuration

language: "en-US"

reviews:
  profile: "chill"

  auto_review:
    enabled: true
    drafts: false
    auto_incremental_review: false

  # Skip non-code files
  path_filters:
    - "!.state/**"
    - "!*.md"
    - "!.github/**"

  tools:
    clippy:
      enabled: true
    semgrep:
      enabled: true

chat:
  auto_reply: false
