# CodeRabbit Configuration
# https://docs.coderabbit.ai/reference/configuration

language: "en-US"

reviews:
  # "chill" = less nitpicky, focus on important issues
  profile: "chill"

  auto_review:
    enabled: true
    drafts: false
    # Only review on PR open, NOT on every push
    auto_incremental_review: false

  # Only review actual code, skip docs/state files
  path_filters:
    - "!.state/**"
    - "!*.md"
    - "!.github/**"

  # Minimal guidance - let CodeRabbit do its thing
  path_instructions:
    - path: "src/**/*.rs"
      instructions: "Rust CLI tool. Focus on error handling and safety."

  tools:
    clippy:
      enabled: true
    semgrep:
      enabled: true

chat:
  auto_reply: false
