.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH edit 1  "edit " 
.SH NAME
edit \- Open configuration file in your default editor
.SH SYNOPSIS
\fBedit\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Open the configuration file in your default editor.
.PP
Uses the $EDITOR environment variable (defaults to \*(Aqvi\*(Aq).
Config file location: ~/.config/agr/config.toml
.PP
EXAMPLE:
    agr config edit
    EDITOR=nano agr config edit
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
